language: node_js
node_js:
- '8'
cache: yarn
install:
- yarn
script:
- yarn run build
deploy:
  provider: s3
  access_key_id:
    secure: HjX5f2SHtDO91qhb7+r4hl3eS63bGMTZN+aJ1fI1GbZAOTDUh2PtW0R4YmkhUmOE9hQSrY5tleFlrNnezNMxl9a+QfLADm01RtL3ZaxyWsjmnUcUgQyxUos7HC2PdpcgpqL3k3jgn/Vh5FvjSNSH+Dfchag9iaSmrW/oikYKmVjD5Dk02e40a/a/Ygl+vONLGwAssnUkvysgkeApW4C0SMpcXGVWiVNAJOulg1pjxve0slTkxf8TmjHShA5xlAGK/tduUIaLB5pBB+MSAb9a/OYhUpPE5zGx5VpKY32OKmhWc48KygXTTMIwg8N/a3Gny2/qo1fpBm16csP8oc4zx9wTn2crdP9I9zVT5vI8/iIu++PcwAFtsytaYAgfCced8CwI0qXU2UIi+m4Yawa3JbJCXC//r+JFCGt/IlQ1paWLvuFvqppCt8Pwx9QVWXtUbrqtvOx1cPyf0o1WP97lGUz11HucfqFgZmYAjPOF3I8UQLsvDpyZlu9DT6Af12QGXjhIYJpJ4xerJJ5C/Wkq1HJbLGlo97SfYe2g+5Nu/LKCVfwlHWlfxs5R5ZWGVxWFZ6PaIrdQo8e961z1WuK7+nqC1f4jY4JiZJvKzn9IV9nJOn+kwlJrPOlBzKcGFQ1M7oWfaoNS+KDpKTe2Z+8sF/yZAJ05TkaHDdehqVz/ujk=
  secret_access_key:
    secure: DwPkSk1RWRH5vj/98LQ100I38kh0Zn50zuLLJgTMRAPkBg5MKiqFD+JN8aTQU8GrQ0qiq+mhokSVuwHKy4sS/QmUAl3mW0LGMY12ywJL4INFRoiH0FvjuvaM0omTw5J6fGv/2kVbAfyzXW7D7R61xjyNPPvDI+vYq8uUU4ol71eSZt54Chq7wzay7H0QwFz/fDUL78ReFZHRbR+0jCKya+k9atMh/DFo4HuhwkVNltF63xYMGEQCeprhbyKhQfSTc5MzsicNd84nVGdKWOi2LdZTAdP7ZH03L416EyILqNR5uthtWSNPxgoRSz5YuXAMjMsC9VG3rZG0ANXssiDFoyLUXFlR7ThXp2hwWyVLyRcagWAZL3KCjl5JRjrTERiJf6dUsY4FfbyJpxiat420615tpLY90W4HUA/w2ba6FkbilLOwTEQW+kNv/TboOTZuDr8d15gg8w7bGzKWgf/td86CCv9vqnSgq5EUzD/SDGFcXo1wjRVPKxqvSZYQCFkfzqLRl/Oi2tIsGt7/Grezi7OLOho/L/m89AM/x3U+Bk9dberaBoLbH0cYgGSwG5XSPzy8RpKMoEsKlEiVVY1iarkHErntM6+6FgHfmeBC/89dkyEb57CsG07OfvqyyB39pI7LbY3J0v/mjbYatpHyBxtsiVp8F0YPU5R9lhmrHGA=
  bucket: markdowner.io
  local_dir: ./dist/
  skip_cleanup: false
  region: eu-west-1
  on:
    branch: master
